"""
services/tts_engine.py — Modular Text-to-Speech Engine for Shorts Production.

Provides unified, production-grade speech synthesis with:
  1. Piper TTS: Fast, local, offline neural speech synthesis (el_GR-rapunzelina-medium/low).
  2. Edge-TTS: Fallback online Microsoft neural voice synthesis (el-GR-NestorasNeural/AthinaNeural).
  3. Automatic sentence boundary tracking & word-level timestamp generation for dynamic karaoke captions.
  4. Automatic voice model fetching and memory-cached inference sessions.
  5. Greek channel and phonetic pronunciation sanitization.
"""

from __future__ import annotations

import asyncio
import logging
import re
import shutil
import subprocess
import wave
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

try:
    from config import APP_ROOT
except ImportError:
    from shorts_engine.config import APP_ROOT

try:
    from services.transcriber import TranscriptionSegment
except ImportError:
    from shorts_engine.services.transcriber import TranscriptionSegment

try:
    from services.video_engine import probe_duration
except ImportError:
    from shorts_engine.services.video_engine import probe_duration

logger = logging.getLogger(__name__)

DEFAULT_PIPER_VOICE = "el_GR-rapunzelina-medium"
DEFAULT_EDGE_VOICE = "el-GR-NestorasNeural"
DEFAULT_VOICE = DEFAULT_EDGE_VOICE
PIPER_MODELS_DIR = APP_ROOT / "assets" / "models" / "piper"

SUPPORTED_PIPER_VOICES: list[str] = [
    "el_GR-rapunzelina-medium",
    "el_GR-rapunzelina-low",
    "en_US-lessac-medium",
    "en_US-amy-medium",
]

SUPPORTED_EDGE_VOICES: list[str] = [
    "el-GR-NestorasNeural",
    "el-GR-AthinaNeural",
    "en-US-GuyNeural",
    "en-US-JennyNeural",
]

# Preset mappings for specialized vocal styles
VOICE_PRESET_PROSODY: dict[str, dict[str, str]] = {
    "el-GR-NestorasNeural": {"pitch": "-4Hz", "voice": "el-GR-NestorasNeural"},
    "el-GR-Nestoras-Deep": {"pitch": "-7Hz", "voice": "el-GR-NestorasNeural"},
    "el-GR-AthinaNeural": {"pitch": "+0Hz", "voice": "el-GR-AthinaNeural"},
}


def sanitize_voiceover_speech(text: str) -> str:
    """
    Sanitize text to guarantee natural Greek pronunciation of brand names,
    strip unwanted markdown formatting, and normalize spacing.
    """
    cleaned = text.strip()
    if not cleaned:
        return ""

    # Ensure Greek pronunciation for Dianisma / Diansma in speech synthesis
    cleaned = re.sub(r"\bκανάλι\s+[@#]?dianismanews\b", "κανάλι Διάνυσμα", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bκανάλι\s+[@#]?dianisma\b", "κανάλι Διάνυσμα", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"[@#]?dianismanews\b", "κανάλι Διάνυσμα", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(
        r"\b(στο|από|για|το|του|των|με|σε)\s+dianisma\b",
        r"\1 Διάνυσμα",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(
        r"\b(στο|από|για|το|του|των|με|σε)\s+diansma\b",
        r"\1 Διάνυσμα",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(r"[@#]?dianisma\b", "Διάνυσμα", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"[@#]?diansma\b", "Διάνυσμα", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bκανάλι\s+κανάλι\b", "κανάλι", cleaned, flags=re.IGNORECASE)

    # Strip code fences, asterisks, brackets often generated by LLMs
    cleaned = re.sub(r"[*_`#~]", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


class TTSEngine(ABC):
    """Abstract Base Class for Text-to-Speech synthesis engines."""

    @abstractmethod
    def synthesize(
        self,
        text: str,
        output_path: Path,
        voice: str | None = None,
        speed: float = 1.0,
    ) -> tuple[Path, list[TranscriptionSegment]]:
        """
        Synthesize text to audio and return the output path and aligned transcript segments.
        """
        pass


class PiperTTSEngine(TTSEngine):
    """
    High-performance, local offline neural TTS engine using Piper ONNX models.
    Runs entirely on CPU with zero cloud dependencies and generates exact sentence chunks.
    """

    def __init__(self, models_dir: Path | None = None) -> None:
        self.models_dir = models_dir if models_dir is not None else PIPER_MODELS_DIR
        self.models_dir.mkdir(parents=True, exist_ok=True)
        self._voice_cache: dict[str, Any] = {}

    def ensure_voice_downloaded(self, voice_name: str) -> tuple[Path, Path]:
        """
        Ensure the ONNX model and config files exist locally, downloading if missing.
        """
        model_path = self.models_dir / f"{voice_name}.onnx"
        config_path = self.models_dir / f"{voice_name}.onnx.json"

        if (
            model_path.is_file()
            and model_path.stat().st_size > 0
            and config_path.is_file()
            and config_path.stat().st_size > 0
        ):
            return model_path, config_path

        logger.info("Downloading Piper voice model '%s' to '%s'...", voice_name, self.models_dir)
        try:
            from piper.download_voices import download_voice

            download_voice(voice_name, self.models_dir)
        except Exception as exc:
            logger.error("Failed downloading Piper voice '%s': %s", voice_name, exc)
            raise RuntimeError(f"Failed downloading Piper voice model '{voice_name}': {exc}") from exc

        if not model_path.is_file() or not config_path.is_file():
            raise FileNotFoundError(f"Piper model files missing after download: {model_path}")

        return model_path, config_path

    def get_piper_voice(self, voice_name: str) -> Any:
        """
        Load and cache a PiperVoice instance in memory.
        """
        if voice_name in self._voice_cache:
            return self._voice_cache[voice_name]

        model_path, config_path = self.ensure_voice_downloaded(voice_name)
        try:
            from piper import PiperVoice

            voice = PiperVoice.load(model_path, config_path=config_path)
            self._voice_cache[voice_name] = voice
            return voice
        except Exception as exc:
            logger.error("Failed loading PiperVoice for '%s': %s", voice_name, exc)
            raise RuntimeError(f"Failed loading PiperVoice '{voice_name}': {exc}") from exc

    def synthesize(
        self,
        text: str,
        output_path: Path,
        voice: str | None = None,
        speed: float = 1.0,
    ) -> tuple[Path, list[TranscriptionSegment]]:
        """
        Synthesize text into WAV or MP3 and compute aligned TranscriptionSegments.
        """
        clean_text = sanitize_voiceover_speech(text)
        if not clean_text:
            raise ValueError("Cannot synthesize empty text.")

        active_voice = voice if voice and voice in SUPPORTED_PIPER_VOICES else DEFAULT_PIPER_VOICE
        piper_voice = self.get_piper_voice(active_voice)

        # Piper length_scale: 1.0 is normal, < 1.0 is faster, > 1.0 is slower.
        safe_speed = max(0.5, min(2.0, speed))
        length_scale = 1.0 / safe_speed

        try:
            from piper.config import SynthesisConfig

            syn_config = SynthesisConfig(length_scale=length_scale)
        except Exception:
            syn_config = None

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        is_mp3 = output_path.suffix.lower() == ".mp3"
        temp_wav = output_path.with_suffix(".temp.wav") if is_mp3 else output_path

        # Split sentences from raw text to pair with chunks
        raw_sentences = [
            s.strip()
            for s in re.split(r"(?<=[.!?;…\n])\s+", clean_text)
            if s.strip()
        ]
        if not raw_sentences:
            raw_sentences = [clean_text]

        # Synthesize chunks and collect audio
        chunks = list(piper_voice.synthesize(clean_text, syn_config=syn_config))
        if not chunks:
            raise RuntimeError("Piper synthesis returned 0 audio chunks.")

        sample_rate = chunks[0].sample_rate
        with wave.open(str(temp_wav), "wb") as wav_file:
            wav_file.setframerate(sample_rate)
            wav_file.setsampwidth(2)
            wav_file.setnchannels(1)
            for chunk in chunks:
                wav_file.writeframes(chunk.audio_int16_bytes)

        if is_mp3:
            # Convert WAV to MP3 using FFmpeg
            ffmpeg_cmd = [
                "ffmpeg",
                "-y",
                "-i",
                str(temp_wav),
                "-c:a",
                "libmp3lame",
                "-q:a",
                "2",
                str(output_path),
            ]
            try:
                subprocess.run(
                    ffmpeg_cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    check=True,
                )
            except Exception as exc:
                logger.warning("FFmpeg WAV->MP3 conversion failed (%s), keeping WAV.", exc)
                shutil.move(temp_wav, output_path)
            else:
                if temp_wav.is_file():
                    temp_wav.unlink(missing_ok=True)

        # Build segments and word-level timestamps
        segments: list[TranscriptionSegment] = []
        cur_start = 0.0

        num_chunks = len(chunks)
        num_sentences = len(raw_sentences)

        if num_chunks == num_sentences:
            sentence_pairs = zip(raw_sentences, chunks)
            for s_text, chunk in sentence_pairs:
                c_dur = len(chunk.audio_float_array) / float(chunk.sample_rate)
                s_start = round(cur_start, 3)
                s_end = round(cur_start + c_dur, 3)
                cur_start = s_end

                words_list = s_text.split()
                word_tuples: list[tuple[float, float, str]] = []
                if words_list:
                    total_chars = max(1, sum(len(w) for w in words_list))
                    cur_w_start = s_start
                    for w_idx, w in enumerate(words_list):
                        if w_idx == len(words_list) - 1:
                            cur_w_end = s_end
                        else:
                            w_dur = (len(w) / total_chars) * c_dur
                            cur_w_end = cur_w_start + w_dur
                        word_tuples.append((
                            round(cur_w_start, 3),
                            round(max(cur_w_start + 0.06, cur_w_end), 3),
                            w,
                        ))
                        cur_w_start = cur_w_end

                segments.append(
                    TranscriptionSegment(
                        start=s_start,
                        end=s_end,
                        text=s_text,
                        words=word_tuples,
                    )
                )
        else:
            # Distribute proportionally across all sentences
            total_dur = sum(len(c.audio_float_array) / float(c.sample_rate) for c in chunks)
            total_chars = max(1, sum(len(s) for s in raw_sentences))
            for s_idx, s_text in enumerate(raw_sentences):
                if s_idx == len(raw_sentences) - 1:
                    s_end = total_dur
                else:
                    s_dur = (len(s_text) / total_chars) * total_dur
                    s_end = cur_start + s_dur

                s_start = round(cur_start, 3)
                s_end = round(s_end, 3)
                cur_start = s_end

                words_list = s_text.split()
                word_tuples = []
                if words_list:
                    w_total_chars = max(1, sum(len(w) for w in words_list))
                    cur_w_start = s_start
                    s_dur = max(0.1, s_end - s_start)
                    for w_idx, w in enumerate(words_list):
                        if w_idx == len(words_list) - 1:
                            cur_w_end = s_end
                        else:
                            w_dur = (len(w) / w_total_chars) * s_dur
                            cur_w_end = cur_w_start + w_dur
                        word_tuples.append((
                            round(cur_w_start, 3),
                            round(max(cur_w_start + 0.06, cur_w_end), 3),
                            w,
                        ))
                        cur_w_start = cur_w_end

                segments.append(
                    TranscriptionSegment(
                        start=s_start,
                        end=s_end,
                        text=s_text,
                        words=word_tuples,
                    )
                )

        logger.info(
            "Synthesized %d segments (%.2fs) with Piper '%s' -> %s",
            len(segments),
            segments[-1].end if segments else 0.0,
            active_voice,
            output_path.name,
        )
        return output_path, segments


class EdgeTTSEngine(TTSEngine):
    """
    Cloud-based neural TTS engine using Microsoft Edge TTS.
    """

    async def _async_synthesize(
        self,
        clean_text: str,
        output_path: Path,
        voice: str,
        speed: float = 1.0,
        pitch: str | None = None,
    ) -> list[TranscriptionSegment]:
        import edge_tts

        rate_str = f"+{int(round((speed - 1.0) * 100))}%" if speed >= 1.0 else f"{int(round((speed - 1.0) * 100))}%"
        active_pitch = pitch if pitch is not None else VOICE_PRESET_PROSODY.get(voice, {}).get("pitch", "-4Hz")

        # Use WordBoundary (not SentenceBoundary) so every spoken word carries its own
        # exact offset + duration in 100-nanosecond ticks.  SentenceBoundary only marks
        # the sentence envelope and forces us to interpolate word times from character
        # counts — which is inaccurate for Greek (syllable weight varies a lot) and also
        # drifts due to Microsoft's tick-counter integer overflow on texts > ~60 s.
        comm = edge_tts.Communicate(
            clean_text, voice, rate=rate_str, pitch=active_pitch, boundary="WordBoundary"
        )
        audio_bytes = bytearray()
        raw_words: list[dict[str, Any]] = []

        async for chunk in comm.stream():
            chunk_type = chunk.get("type")
            if chunk_type == "audio":
                audio_bytes.extend(chunk.get("data", b""))
            elif chunk_type == "WordBoundary":
                raw_words.append(chunk)
            # SentenceBoundary events are ignored — we reconstruct sentence groups below.

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(audio_bytes)
        if not output_path.is_file() or output_path.stat().st_size == 0:
            raise RuntimeError(f"Edge-TTS synthesis produced empty file at {output_path}")

        # Convert 100-nanosecond tick offsets to seconds and build word tuples.
        TICKS_PER_SEC = 10_000_000.0
        MIN_WORD_DUR = 0.06  # floor to prevent zero-width words

        flat_words: list[tuple[float, float, str]] = []
        for w in raw_words:
            w_text = str(w.get("text", "")).strip()
            if not w_text:
                continue
            w_start = float(w.get("offset", 0)) / TICKS_PER_SEC
            w_dur = float(w.get("duration", 0)) / TICKS_PER_SEC
            w_end = max(w_start + MIN_WORD_DUR, w_start + w_dur)
            flat_words.append((round(w_start, 3), round(w_end, 3), w_text))

        if not flat_words:
            # Fallback: single segment covering the full file, with character-proportional words
            dur = probe_duration(output_path)
            words_list = clean_text.split()
            total_chars = max(1, sum(len(w) for w in words_list))
            word_tuples: list[tuple[float, float, str]] = []
            cur_start = 0.0
            for w_idx, w in enumerate(words_list):
                if w_idx == len(words_list) - 1:
                    cur_end = dur
                else:
                    w_dur_fb = (len(w) / total_chars) * dur
                    cur_end = cur_start + w_dur_fb
                word_tuples.append((
                    round(cur_start, 3),
                    round(max(cur_start + MIN_WORD_DUR, cur_end), 3),
                    w,
                ))
                cur_start = cur_end
            return [TranscriptionSegment(start=0.0, end=round(dur, 3), text=clean_text, words=word_tuples)]

        # Group flat word list into sentence-level TranscriptionSegments by detecting
        # sentence-terminal punctuation on each word.  This keeps the downstream
        # segment structure intact (e.g. SEO, logic guardrail) while word-level
        # timestamps remain exact.
        _SENTENCE_END = (".", "!", "?", "…", ";")
        segments: list[TranscriptionSegment] = []
        current_words: list[tuple[float, float, str]] = []

        for word_tuple in flat_words:
            current_words.append(word_tuple)
            stripped = word_tuple[2].rstrip("\"'»")
            if stripped.endswith(_SENTENCE_END) and len(current_words) >= 2:
                seg_text = " ".join(w[2] for w in current_words)
                segments.append(TranscriptionSegment(
                    start=current_words[0][0],
                    end=current_words[-1][1],
                    text=seg_text,
                    words=list(current_words),
                ))
                current_words = []

        # Flush any remaining words that didn't end with a sentence terminator
        if current_words:
            seg_text = " ".join(w[2] for w in current_words)
            segments.append(TranscriptionSegment(
                start=current_words[0][0],
                end=current_words[-1][1],
                text=seg_text,
                words=list(current_words),
            ))

        logger.info(
            "Edge-TTS synthesized %d words → %d segments (%.2fs) with '%s'",
            len(flat_words),
            len(segments),
            segments[-1].end if segments else 0.0,
            voice,
        )
        return segments

    def synthesize(
        self,
        text: str,
        output_path: Path,
        voice: str | None = None,
        speed: float = 1.0,
        pitch: str | None = None,
    ) -> tuple[Path, list[TranscriptionSegment]]:
        clean_text = sanitize_voiceover_speech(text)
        if not clean_text:
            raise ValueError("Cannot synthesize empty text.")

        active_voice = voice if voice and ("Neural" in voice or "el-GR-" in voice) else DEFAULT_EDGE_VOICE
        preset_info = VOICE_PRESET_PROSODY.get(active_voice, {})
        target_voice = preset_info.get("voice", active_voice)
        target_pitch = pitch if pitch is not None else preset_info.get("pitch", "-4Hz")

        logger.info(
            "Synthesizing mature Greek voiceover with Edge-TTS ('%s', pitch: %s)...",
            target_voice,
            target_pitch,
        )
        segments = asyncio.run(
            self._async_synthesize(clean_text, output_path, target_voice, speed=speed, pitch=target_pitch)
        )
        return output_path, segments


# ── Global Engine Registry ───────────────────────────────────────────────────

_ENGINES: dict[str, TTSEngine] = {
    "piper": PiperTTSEngine(),
    "edge": EdgeTTSEngine(),
}


def get_tts_engine(engine_name: str = "edge") -> TTSEngine:
    """
    Retrieve a singleton TTSEngine instance by name ('edge' or 'piper').
    """
    engine_key = engine_name.lower().strip()
    if engine_key not in _ENGINES:
        logger.warning("Unknown TTS engine '%s', falling back to 'edge'.", engine_name)
        engine_key = "edge"
    return _ENGINES[engine_key]


def synthesize_voiceover_with_segments(
    text: str,
    output_path: Path,
    voice: str | None = None,
    engine: str | None = None,
    speed: float = 1.0,
    pitch: str | None = None,
) -> tuple[Path, list[TranscriptionSegment]]:
    """
    Unified entrypoint for voiceover synthesis with boundary-aligned segments.
    Defaults to authoritative mature male Greek voice (NestorasNeural with -4Hz pitch tuning).
    """
    # Auto-route based on voice naming if engine is not explicitly forced
    if engine is None:
        if voice and ("rapunzelina" in voice or "lessac" in voice or "amy" in voice):
            engine = "piper"
        else:
            engine = "edge"

    active_voice = voice if voice is not None else (DEFAULT_EDGE_VOICE if engine == "edge" else DEFAULT_PIPER_VOICE)
    tts_engine = get_tts_engine(engine)

    try:
        if isinstance(tts_engine, EdgeTTSEngine):
            return tts_engine.synthesize(text, output_path, voice=active_voice, speed=speed, pitch=pitch)
        return tts_engine.synthesize(text, output_path, voice=active_voice, speed=speed)
    except Exception as exc:
        if engine == "edge":
            logger.warning("Edge-TTS synthesis failed (%s), falling back to Piper...", exc)
            fallback_engine = get_tts_engine("piper")
            return fallback_engine.synthesize(
                text, output_path, voice=DEFAULT_PIPER_VOICE, speed=speed
            )
        elif engine == "piper":
            logger.warning("Piper synthesis failed (%s), falling back to Edge-TTS...", exc)
            fallback_engine = get_tts_engine("edge")
            return fallback_engine.synthesize(
                text, output_path, voice=DEFAULT_EDGE_VOICE, speed=speed, pitch=pitch
            )
        raise


def synthesize_voiceover(
    text: str,
    output_path: Path,
    voice: str | None = None,
    engine: str | None = None,
    speed: float = 1.0,
    pitch: str | None = None,
) -> Path:
    """
    Unified entrypoint for synthesizing voiceover audio file.
    """
    path, _ = synthesize_voiceover_with_segments(
        text, output_path, voice=voice, engine=engine, speed=speed, pitch=pitch
    )
    return path
